apiVersion: apps/v1
kind: Deployment
metadata: 
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec: 
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector: 
    matchLabels: 
      app: k8s-bigip-ctlr
  strategy: 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: k8s-bigip-ctlr
      name: k8s-bigip-ctlr
    spec: 
      containers: 
        - 
          args: 
            # See https://clouddocs.f5.com/containers/latest/userguide/config-parameters.html
            # for more configuration options.
            - "--credentials-directory=/tmp/creds"
            - "--bigip-partition=CIS1"
            - "--pool-member-type=nodeport"
            - "--insecure=true"
            - "--custom-resource-mode=true"
            - "--node-label-selector=node-role.kubernetes.io/worker"
          command: 
            - /app/bin/k8s-bigip-ctlr
          env: 
            - 
              name: BIGIP_USERNAME
              valueFrom: 
                secretKeyRef: 
                  key: username
                  name: bigip-login
            - 
              name: BIGIP_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  key: password
                  name: bigip-login
          image: "f5networks/k8s-bigip-ctlr:latest"   
          name: f5-server
          volumeMounts:
          - name: tmp-creds
            mountPath: "/tmp/creds"
            readOnly: true
      volumes:
      - name: tmp-creds
        secret:
          secretName: bip-creds
      serviceAccountName: bigip-ctlr

