apiVersion: v1
kind: Service
metadata:
  labels:
    cis.f5.com/as3-tenant: AS3CM
    cis.f5.com/as3-app: A1
    cis.f5.com/as3-pool: web_pool
  name: myservice
  namespace: projectone
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ngxdc
  type: NodePort
