apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: crd-vs
  labels:
    f5cr: "true"
spec:
  # This is an insecure virtual, Please use TLSProfile to secure the virtual
  # check out tls examples to understand more.
  host: crd.aditf5.com
  virtualServerAddress: "10.0.1.7"
  virtualServerHTTPPort: 80
  virtualServerName: "crd_vs"
  pools:
  - path: /
    service: myservice
    servicePort: 8080
