apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: ngxdcvs-vs
  labels:
    f5cr: "true"
spec:
  # This is an insecure virtual, Please use TLSProfile to secure the virtual
  # check out tls examples to understand more.
  host: host3.com
  virtualServerAddress: "10.0.1.7"
  virtualServerHTTPPort: 80
  virtualServerName: "ngxdcnpvs_vs"
  pools:
  - path: /
    service: ngxdcnp
    servicePort: 8080
