apiVersion: v1
kind: ConfigMap
metadata:
  name: cis-as3-cm
  namespace: projectone
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "cis-as3-cm",
            "remark": "AS3CM",
            "label": "AS3CM",
            "AS3CM": {
                "class": "Tenant",
                "A1": {
                    "class": "Application",
                    "template": "generic",
                    "as3cm_a1_80_vs": {
                        "class": "Service_HTTP",
                        "remark": "as3cm_a1",
                        "virtualAddresses": [
                            "10.0.1.11"
                        ],
                        "pool": "web_pool"
                    },
                    "web_pool": {
                        "class": "Pool",
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
